"""call management

Revision ID: fdfdd3879577
Revises: ca0cd41c1454
Create Date: 2026-07-26 00:37:55.502592+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.calls.models.types import NEW_ENUMS

# revision identifiers, used by Alembic.
revision: str = 'fdfdd3879577'
down_revision: str | None = 'ca0cd41c1454'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create the new native enum types once.
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('direction', postgresql.ENUM('inbound', 'outbound', name='call_direction', create_type=False), server_default='inbound', nullable=False),
    sa.Column('call_type', postgresql.ENUM('emergency', 'service', 'information', 'test', 'callback', 'other', name='call_type', create_type=False), server_default='emergency', nullable=False),
    sa.Column('source', postgresql.ENUM('phone', 'mobile', 'sip', 'webrtc', 'radio', 'manual', 'other', name='call_source', create_type=False), server_default='phone', nullable=False),
    sa.Column('status', postgresql.ENUM('new', 'ringing', 'accepted', 'in_progress', 'linked', 'completed', 'cancelled', 'error', name='call_status', create_type=False), server_default='new', nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'normal', 'high', 'critical', name='call_priority', create_type=False), server_default='normal', nullable=False),
    sa.Column('caller_number', sa.String(length=64), nullable=True),
    sa.Column('caller_name', sa.String(length=255), nullable=True),
    sa.Column('callee_number', sa.String(length=64), nullable=True),
    sa.Column('address_hint', sa.String(length=512), nullable=True),
    sa.Column('dispatcher_user_id', sa.UUID(), nullable=True),
    sa.Column('dispatcher_name', sa.String(length=255), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wait_seconds', sa.Integer(), nullable=True),
    sa.Column('talk_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['dispatcher_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_call_type'), 'calls', ['call_type'], unique=False)
    op.create_index(op.f('ix_calls_caller_number'), 'calls', ['caller_number'], unique=False)
    op.create_index(op.f('ix_calls_dispatcher_user_id'), 'calls', ['dispatcher_user_id'], unique=False)
    op.create_index(op.f('ix_calls_external_id'), 'calls', ['external_id'], unique=False)
    op.create_index(op.f('ix_calls_incident_id'), 'calls', ['incident_id'], unique=False)
    op.create_index(op.f('ix_calls_is_deleted'), 'calls', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_calls_number'), 'calls', ['number'], unique=True)
    op.create_index(op.f('ix_calls_priority'), 'calls', ['priority'], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)
    op.create_index('ix_calls_status_created', 'calls', ['status', 'created_at'], unique=False)
    op.create_table('call_history',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('created', 'status_changed', 'queued', 'dequeued', 'dispatcher_assigned', 'answered', 'incident_created', 'incident_linked', 'participant_added', 'recording_registered', 'transcript_registered', 'provider_action', 'completed', 'cancelled', 'error', name='call_event_type', create_type=False), nullable=False),
    sa.Column('from_status', postgresql.ENUM('new', 'ringing', 'accepted', 'in_progress', 'linked', 'completed', 'cancelled', 'error', name='call_status', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM('new', 'ringing', 'accepted', 'in_progress', 'linked', 'completed', 'cancelled', 'error', name='call_status', create_type=False), nullable=True),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='dispatcher', nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_history_call_id'), 'call_history', ['call_id'], unique=False)
    op.create_index('ix_call_history_call_time', 'call_history', ['call_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_call_history_event_type'), 'call_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_call_history_is_deleted'), 'call_history', ['is_deleted'], unique=False)
    op.create_index('ix_call_history_time', 'call_history', ['occurred_at'], unique=False)
    op.create_table('call_incident_links',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('link_type', postgresql.ENUM('created', 'linked', name='call_link_type', create_type=False), server_default='linked', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'incident_id', name='uq_call_incident_link')
    )
    op.create_index(op.f('ix_call_incident_links_call_id'), 'call_incident_links', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_incident_links_incident_id'), 'call_incident_links', ['incident_id'], unique=False)
    op.create_index(op.f('ix_call_incident_links_is_deleted'), 'call_incident_links', ['is_deleted'], unique=False)
    op.create_table('call_metadata',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'key', name='uq_call_metadata_key')
    )
    op.create_index(op.f('ix_call_metadata_call_id'), 'call_metadata', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_metadata_is_deleted'), 'call_metadata', ['is_deleted'], unique=False)
    op.create_table('call_participants',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('caller', 'dispatcher', 'transferred', 'observer', 'other', name='call_participant_role', create_type=False), server_default='caller', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_participants_call_id'), 'call_participants', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_participants_is_deleted'), 'call_participants', ['is_deleted'], unique=False)
    op.create_table('call_queue',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'normal', 'high', 'critical', name='call_priority', create_type=False), server_default='normal', nullable=False),
    sa.Column('status', postgresql.ENUM('waiting', 'assigned', 'in_progress', 'done', 'abandoned', name='call_queue_status', create_type=False), server_default='waiting', nullable=False),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatcher_user_id', sa.UUID(), nullable=True),
    sa.Column('dispatcher_name', sa.String(length=255), nullable=True),
    sa.Column('workstation', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispatcher_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', name='uq_call_queue_call')
    )
    op.create_index(op.f('ix_call_queue_call_id'), 'call_queue', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_queue_dispatcher_user_id'), 'call_queue', ['dispatcher_user_id'], unique=False)
    op.create_index(op.f('ix_call_queue_is_deleted'), 'call_queue', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_call_queue_status'), 'call_queue', ['status'], unique=False)
    op.create_index('ix_call_queue_status_priority', 'call_queue', ['status', 'priority'], unique=False)
    op.create_table('call_recordings',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('audio_format', sa.String(length=32), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('storage_ref', sa.String(length=512), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'available', 'processing', 'failed', 'deleted', name='call_recording_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_recordings_call_id'), 'call_recordings', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_recordings_is_deleted'), 'call_recordings', ['is_deleted'], unique=False)
    op.create_table('call_transcripts',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='call_transcript_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_transcripts_call_id'), 'call_transcripts', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_transcripts_is_deleted'), 'call_transcripts', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_transcripts_is_deleted'), table_name='call_transcripts')
    op.drop_index(op.f('ix_call_transcripts_call_id'), table_name='call_transcripts')
    op.drop_table('call_transcripts')
    op.drop_index(op.f('ix_call_recordings_is_deleted'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_call_id'), table_name='call_recordings')
    op.drop_table('call_recordings')
    op.drop_index('ix_call_queue_status_priority', table_name='call_queue')
    op.drop_index(op.f('ix_call_queue_status'), table_name='call_queue')
    op.drop_index(op.f('ix_call_queue_is_deleted'), table_name='call_queue')
    op.drop_index(op.f('ix_call_queue_dispatcher_user_id'), table_name='call_queue')
    op.drop_index(op.f('ix_call_queue_call_id'), table_name='call_queue')
    op.drop_table('call_queue')
    op.drop_index(op.f('ix_call_participants_is_deleted'), table_name='call_participants')
    op.drop_index(op.f('ix_call_participants_call_id'), table_name='call_participants')
    op.drop_table('call_participants')
    op.drop_index(op.f('ix_call_metadata_is_deleted'), table_name='call_metadata')
    op.drop_index(op.f('ix_call_metadata_call_id'), table_name='call_metadata')
    op.drop_table('call_metadata')
    op.drop_index(op.f('ix_call_incident_links_is_deleted'), table_name='call_incident_links')
    op.drop_index(op.f('ix_call_incident_links_incident_id'), table_name='call_incident_links')
    op.drop_index(op.f('ix_call_incident_links_call_id'), table_name='call_incident_links')
    op.drop_table('call_incident_links')
    op.drop_index('ix_call_history_time', table_name='call_history')
    op.drop_index(op.f('ix_call_history_is_deleted'), table_name='call_history')
    op.drop_index(op.f('ix_call_history_event_type'), table_name='call_history')
    op.drop_index('ix_call_history_call_time', table_name='call_history')
    op.drop_index(op.f('ix_call_history_call_id'), table_name='call_history')
    op.drop_table('call_history')
    op.drop_index('ix_calls_status_created', table_name='calls')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_priority'), table_name='calls')
    op.drop_index(op.f('ix_calls_number'), table_name='calls')
    op.drop_index(op.f('ix_calls_is_deleted'), table_name='calls')
    op.drop_index(op.f('ix_calls_incident_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_external_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_dispatcher_user_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_caller_number'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_type'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###

    # Drop the new native enum types.
    bind = op.get_bind()
    for enum_type in reversed(NEW_ENUMS):
        enum_type.drop(bind, checkfirst=True)
