"""gis geographic core

Revision ID: ef914db8e6d0
Revises: 515744cc4c90
Create Date: 2026-07-24 22:46:06.535552+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'ef914db8e6d0'
down_revision: str | None = '515744cc4c90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('gis_coordinates',
    sa.Column('srid', sa.Integer(), server_default='4326', nullable=False),
    sa.Column('accuracy', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_gis_coordinates_geom', 'gis_coordinates', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_gis_coordinates_is_deleted'), 'gis_coordinates', ['is_deleted'], unique=False)
    op.create_table('gis_geocoding_logs',
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=1024), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('result_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('from_cache', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_geocoding_logs_is_deleted'), 'gis_geocoding_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_gis_geocoding_logs_operation'), 'gis_geocoding_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_gis_geocoding_logs_provider'), 'gis_geocoding_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_gis_geocoding_logs_success'), 'gis_geocoding_logs', ['success'], unique=False)
    op.create_geospatial_table('gis_regions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('administrative_area_id', sa.UUID(), nullable=True),
    sa.Column('boundary', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['administrative_area_id'], ['administrative_areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_geospatial_index('idx_gis_regions_boundary', 'gis_regions', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_gis_regions_administrative_area_id'), 'gis_regions', ['administrative_area_id'], unique=False)
    op.create_index(op.f('ix_gis_regions_is_deleted'), 'gis_regions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_gis_regions_name'), 'gis_regions', ['name'], unique=False)
    op.create_geospatial_table('gis_districts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('boundary', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['gis_regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_gis_districts_boundary', 'gis_districts', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_gis_districts_is_deleted'), 'gis_districts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_gis_districts_name'), 'gis_districts', ['name'], unique=False)
    op.create_index(op.f('ix_gis_districts_region_id'), 'gis_districts', ['region_id'], unique=False)
    op.create_geospatial_table('gis_settlements',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('settlement_type', sa.String(length=64), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('boundary', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['gis_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['gis_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_gis_settlements_boundary', 'gis_settlements', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_gis_settlements_geom', 'gis_settlements', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_gis_settlements_district_id'), 'gis_settlements', ['district_id'], unique=False)
    op.create_index(op.f('ix_gis_settlements_is_deleted'), 'gis_settlements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_gis_settlements_name'), 'gis_settlements', ['name'], unique=False)
    op.create_index(op.f('ix_gis_settlements_region_id'), 'gis_settlements', ['region_id'], unique=False)
    op.create_table('gis_streets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('street_type', sa.String(length=64), nullable=True),
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['gis_settlements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_streets_is_deleted'), 'gis_streets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_gis_streets_name'), 'gis_streets', ['name'], unique=False)
    op.create_index(op.f('ix_gis_streets_settlement_id'), 'gis_streets', ['settlement_id'], unique=False)
    op.create_geospatial_table('gis_buildings',
    sa.Column('house_number', sa.String(length=32), nullable=False),
    sa.Column('block', sa.String(length=32), nullable=True),
    sa.Column('building', sa.String(length=32), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('street_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['street_id'], ['gis_streets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('street_id', 'house_number', 'block', name='uq_building_address')
    )
    op.create_geospatial_index('idx_gis_buildings_geom', 'gis_buildings', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_gis_buildings_is_deleted'), 'gis_buildings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_gis_buildings_street_id'), 'gis_buildings', ['street_id'], unique=False)
    op.create_geospatial_table('gis_addresses',
    sa.Column('raw_address', sa.String(length=1024), nullable=False),
    sa.Column('normalized_address', sa.String(length=1024), nullable=True),
    sa.Column('formatted_address', sa.String(length=1024), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('house_number', sa.String(length=32), nullable=True),
    sa.Column('accuracy', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('is_validated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('settlement_id', sa.UUID(), nullable=True),
    sa.Column('street_id', sa.UUID(), nullable=True),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('coordinate_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['gis_buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coordinate_id'], ['gis_coordinates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['gis_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['gis_regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['gis_settlements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['street_id'], ['gis_streets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_gis_addresses_geom', 'gis_addresses', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_gis_addresses_building_id'), 'gis_addresses', ['building_id'], unique=False)
    op.create_index(op.f('ix_gis_addresses_coordinate_id'), 'gis_addresses', ['coordinate_id'], unique=False)
    op.create_index(op.f('ix_gis_addresses_district_id'), 'gis_addresses', ['district_id'], unique=False)
    op.create_index(op.f('ix_gis_addresses_is_deleted'), 'gis_addresses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_gis_addresses_normalized_address'), 'gis_addresses', ['normalized_address'], unique=False)
    op.create_index(op.f('ix_gis_addresses_region_id'), 'gis_addresses', ['region_id'], unique=False)
    op.create_index(op.f('ix_gis_addresses_settlement_id'), 'gis_addresses', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_gis_addresses_street_id'), 'gis_addresses', ['street_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_addresses_street_id'), table_name='gis_addresses')
    op.drop_index(op.f('ix_gis_addresses_settlement_id'), table_name='gis_addresses')
    op.drop_index(op.f('ix_gis_addresses_region_id'), table_name='gis_addresses')
    op.drop_index(op.f('ix_gis_addresses_normalized_address'), table_name='gis_addresses')
    op.drop_index(op.f('ix_gis_addresses_is_deleted'), table_name='gis_addresses')
    op.drop_index(op.f('ix_gis_addresses_district_id'), table_name='gis_addresses')
    op.drop_index(op.f('ix_gis_addresses_coordinate_id'), table_name='gis_addresses')
    op.drop_index(op.f('ix_gis_addresses_building_id'), table_name='gis_addresses')
    op.drop_geospatial_index('idx_gis_addresses_geom', table_name='gis_addresses', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('gis_addresses')
    op.drop_index(op.f('ix_gis_buildings_street_id'), table_name='gis_buildings')
    op.drop_index(op.f('ix_gis_buildings_is_deleted'), table_name='gis_buildings')
    op.drop_geospatial_index('idx_gis_buildings_geom', table_name='gis_buildings', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('gis_buildings')
    op.drop_index(op.f('ix_gis_streets_settlement_id'), table_name='gis_streets')
    op.drop_index(op.f('ix_gis_streets_name'), table_name='gis_streets')
    op.drop_index(op.f('ix_gis_streets_is_deleted'), table_name='gis_streets')
    op.drop_table('gis_streets')
    op.drop_index(op.f('ix_gis_settlements_region_id'), table_name='gis_settlements')
    op.drop_index(op.f('ix_gis_settlements_name'), table_name='gis_settlements')
    op.drop_index(op.f('ix_gis_settlements_is_deleted'), table_name='gis_settlements')
    op.drop_index(op.f('ix_gis_settlements_district_id'), table_name='gis_settlements')
    op.drop_geospatial_index('idx_gis_settlements_geom', table_name='gis_settlements', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_index('idx_gis_settlements_boundary', table_name='gis_settlements', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('gis_settlements')
    op.drop_index(op.f('ix_gis_districts_region_id'), table_name='gis_districts')
    op.drop_index(op.f('ix_gis_districts_name'), table_name='gis_districts')
    op.drop_index(op.f('ix_gis_districts_is_deleted'), table_name='gis_districts')
    op.drop_geospatial_index('idx_gis_districts_boundary', table_name='gis_districts', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('gis_districts')
    op.drop_index(op.f('ix_gis_regions_name'), table_name='gis_regions')
    op.drop_index(op.f('ix_gis_regions_is_deleted'), table_name='gis_regions')
    op.drop_index(op.f('ix_gis_regions_administrative_area_id'), table_name='gis_regions')
    op.drop_geospatial_index('idx_gis_regions_boundary', table_name='gis_regions', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('gis_regions')
    op.drop_index(op.f('ix_gis_geocoding_logs_success'), table_name='gis_geocoding_logs')
    op.drop_index(op.f('ix_gis_geocoding_logs_provider'), table_name='gis_geocoding_logs')
    op.drop_index(op.f('ix_gis_geocoding_logs_operation'), table_name='gis_geocoding_logs')
    op.drop_index(op.f('ix_gis_geocoding_logs_is_deleted'), table_name='gis_geocoding_logs')
    op.drop_table('gis_geocoding_logs')
    op.drop_index(op.f('ix_gis_coordinates_is_deleted'), table_name='gis_coordinates')
    op.drop_geospatial_index('idx_gis_coordinates_geom', table_name='gis_coordinates', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('gis_coordinates')
    # ### end Alembic commands ###
