"""administration platform

Revision ID: 74a0f4121e60
Revises: 0d42a2ab8331
Create Date: 2026-07-26 10:34:45.245888+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.admin.models.types import NEW_ENUMS

# revision identifiers, used by Alembic.
revision: str = '74a0f4121e60'
down_revision: str | None = '0d42a2ab8331'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create the new native enum types once.
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_statuses',
    sa.Column('login_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_statuses_code'), 'account_statuses', ['code'], unique=True)
    op.create_index(op.f('ix_account_statuses_is_deleted'), 'account_statuses', ['is_deleted'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', postgresql.ENUM('string', 'integer', 'number', 'boolean', 'json', name='admin_setting_type', create_type=False), server_default='string', nullable=False),
    sa.Column('category', postgresql.ENUM('general', 'maps', 'routing', 'ai', 'search', 'dispatch', 'logging', 'notifications', 'integrations', 'security', name='admin_setting_category', create_type=False), server_default='general', nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_category'), 'app_settings', ['category'], unique=False)
    op.create_index(op.f('ix_app_settings_is_deleted'), 'app_settings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('authentication_methods',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', postgresql.ENUM('password', 'ldap', 'active_directory', 'oidc', 'saml', 'other', name='admin_auth_method_kind', create_type=False), server_default='password', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authentication_methods_code'), 'authentication_methods', ['code'], unique=True)
    op.create_index(op.f('ix_authentication_methods_is_deleted'), 'authentication_methods', ['is_deleted'], unique=False)
    op.create_table('integration_providers',
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_providers_code'), 'integration_providers', ['code'], unique=True)
    op.create_index(op.f('ix_integration_providers_is_deleted'), 'integration_providers', ['is_deleted'], unique=False)
    op.create_table('password_policies',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('min_length', sa.Integer(), server_default='8', nullable=False),
    sa.Column('require_uppercase', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('require_lowercase', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('require_digit', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('require_special', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('max_age_days', sa.Integer(), nullable=True),
    sa.Column('history_depth', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_policies_is_deleted'), 'password_policies', ['is_deleted'], unique=False)
    op.create_table('permission_groups',
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_groups_code'), 'permission_groups', ['code'], unique=True)
    op.create_index(op.f('ix_permission_groups_is_deleted'), 'permission_groups', ['is_deleted'], unique=False)
    op.create_table('integrations',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'error', 'degraded', 'unknown', name='admin_integration_status', create_type=False), server_default='inactive', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['integration_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_code'), 'integrations', ['code'], unique=True)
    op.create_index(op.f('ix_integrations_is_deleted'), 'integrations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_integrations_provider_id'), 'integrations', ['provider_id'], unique=False)
    op.create_index(op.f('ix_integrations_status'), 'integrations', ['status'], unique=False)
    op.create_table('permission_group_permissions',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['permission_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'permission_id', name='uq_permission_group_permission')
    )
    op.create_index(op.f('ix_permission_group_permissions_group_id'), 'permission_group_permissions', ['group_id'], unique=False)
    op.create_index(op.f('ix_permission_group_permissions_is_deleted'), 'permission_group_permissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_permission_group_permissions_permission_id'), 'permission_group_permissions', ['permission_id'], unique=False)
    op.create_table('integration_configurations',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'key', name='uq_integration_configuration_key')
    )
    op.create_index(op.f('ix_integration_configurations_integration_id'), 'integration_configurations', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_configurations_is_deleted'), 'integration_configurations', ['is_deleted'], unique=False)
    op.create_table('integration_health_checks',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('healthy', 'degraded', 'unhealthy', 'unknown', name='admin_health_status', create_type=False), server_default='unknown', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_health_checks_integration_id'), 'integration_health_checks', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_health_checks_is_deleted'), 'integration_health_checks', ['is_deleted'], unique=False)
    op.create_table('app_setting_history',
    sa.Column('setting_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_name', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setting_id'], ['app_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_setting_history_is_deleted'), 'app_setting_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_app_setting_history_key'), 'app_setting_history', ['key'], unique=False)
    op.create_index(op.f('ix_app_setting_history_setting_id'), 'app_setting_history', ['setting_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at_session', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_deleted'), 'user_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Seed baseline administration data (idempotent, editable afterwards).
    op.execute(
        """
        INSERT INTO account_statuses
            (id, code, name, description, login_allowed, is_default,
             is_deleted, created_at, updated_at)
        VALUES
            (gen_random_uuid(),'active','Активен',NULL,true,true,false,now(),now()),
            (gen_random_uuid(),'disabled','Отключён',NULL,false,false,false,now(),now()),
            (gen_random_uuid(),'locked','Заблокирован',NULL,false,false,false,now(),now()),
            (gen_random_uuid(),'pending','Ожидает активации',NULL,false,false,false,now(),now())
        ON CONFLICT (code) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO authentication_methods
            (id, code, name, kind, is_enabled, is_default, config,
             is_deleted, created_at, updated_at)
        VALUES
            (gen_random_uuid(),'password','Пароль','password',true,true,NULL,false,now(),now()),
            (gen_random_uuid(),'ldap','LDAP','ldap',false,false,NULL,false,now(),now()),
            (gen_random_uuid(),'active_directory','Active Directory','active_directory',false,false,NULL,false,now(),now()),
            (gen_random_uuid(),'oidc','OpenID Connect','oidc',false,false,NULL,false,now(),now())
        ON CONFLICT (code) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO integration_providers
            (id, code, name, description, kind, is_deleted, created_at, updated_at)
        VALUES
            (gen_random_uuid(),'telephony','Телефония',NULL,'telephony',false,now(),now()),
            (gen_random_uuid(),'gis','Картография',NULL,'gis',false,now(),now()),
            (gen_random_uuid(),'sms','SMS-шлюз',NULL,'sms',false,now(),now()),
            (gen_random_uuid(),'email','Почтовый сервер',NULL,'email',false,now(),now())
        ON CONFLICT (code) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO password_policies
            (id, name, min_length, require_uppercase, require_lowercase,
             require_digit, require_special, max_age_days, history_depth,
             is_default, is_active, is_deleted, created_at, updated_at)
        SELECT gen_random_uuid(),'Стандартная политика',10,true,true,true,false,
               NULL,3,true,true,false,now(),now()
        WHERE NOT EXISTS (SELECT 1 FROM password_policies)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_deleted'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_app_setting_history_setting_id'), table_name='app_setting_history')
    op.drop_index(op.f('ix_app_setting_history_key'), table_name='app_setting_history')
    op.drop_index(op.f('ix_app_setting_history_is_deleted'), table_name='app_setting_history')
    op.drop_table('app_setting_history')
    op.drop_index(op.f('ix_integration_health_checks_is_deleted'), table_name='integration_health_checks')
    op.drop_index(op.f('ix_integration_health_checks_integration_id'), table_name='integration_health_checks')
    op.drop_table('integration_health_checks')
    op.drop_index(op.f('ix_integration_configurations_is_deleted'), table_name='integration_configurations')
    op.drop_index(op.f('ix_integration_configurations_integration_id'), table_name='integration_configurations')
    op.drop_table('integration_configurations')
    op.drop_index(op.f('ix_permission_group_permissions_permission_id'), table_name='permission_group_permissions')
    op.drop_index(op.f('ix_permission_group_permissions_is_deleted'), table_name='permission_group_permissions')
    op.drop_index(op.f('ix_permission_group_permissions_group_id'), table_name='permission_group_permissions')
    op.drop_table('permission_group_permissions')
    op.drop_index(op.f('ix_integrations_status'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_provider_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_is_deleted'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_code'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_permission_groups_is_deleted'), table_name='permission_groups')
    op.drop_index(op.f('ix_permission_groups_code'), table_name='permission_groups')
    op.drop_table('permission_groups')
    op.drop_index(op.f('ix_password_policies_is_deleted'), table_name='password_policies')
    op.drop_table('password_policies')
    op.drop_index(op.f('ix_integration_providers_is_deleted'), table_name='integration_providers')
    op.drop_index(op.f('ix_integration_providers_code'), table_name='integration_providers')
    op.drop_table('integration_providers')
    op.drop_index(op.f('ix_authentication_methods_is_deleted'), table_name='authentication_methods')
    op.drop_index(op.f('ix_authentication_methods_code'), table_name='authentication_methods')
    op.drop_table('authentication_methods')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_is_deleted'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_category'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_account_statuses_is_deleted'), table_name='account_statuses')
    op.drop_index(op.f('ix_account_statuses_code'), table_name='account_statuses')
    op.drop_table('account_statuses')
    # ### end Alembic commands ###

    # Drop the new native enum types.
    bind = op.get_bind()
    for enum_type in reversed(NEW_ENUMS):
        enum_type.drop(bind, checkfirst=True)
