"""create data model schema

Revision ID: 515744cc4c90
Revises: 0001_enable_postgis
Create Date: 2026-07-24 22:26:54.073777+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '515744cc4c90'
down_revision: str | None = '0001_enable_postgis'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('administrative_areas',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('boundary', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['administrative_areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_administrative_area_code')
    )
    op.create_geospatial_index('idx_administrative_areas_boundary', 'administrative_areas', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_administrative_areas_code'), 'administrative_areas', ['code'], unique=False)
    op.create_index(op.f('ix_administrative_areas_is_deleted'), 'administrative_areas', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_administrative_areas_parent_id'), 'administrative_areas', ['parent_id'], unique=False)
    op.create_table('availability_statuses',
    sa.Column('is_operational', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_available_for_dispatch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_statuses_code'), 'availability_statuses', ['code'], unique=True)
    op.create_index(op.f('ix_availability_statuses_is_deleted'), 'availability_statuses', ['is_deleted'], unique=False)
    op.create_table('capabilities',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_code'), 'capabilities', ['code'], unique=True)
    op.create_index(op.f('ix_capabilities_is_deleted'), 'capabilities', ['is_deleted'], unique=False)
    op.create_table('equipment_types',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_types_code'), 'equipment_types', ['code'], unique=True)
    op.create_index(op.f('ix_equipment_types_is_deleted'), 'equipment_types', ['is_deleted'], unique=False)
    op.create_table('incident_types',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['incident_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_types_code'), 'incident_types', ['code'], unique=True)
    op.create_index(op.f('ix_incident_types_is_deleted'), 'incident_types', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_incident_types_parent_id'), 'incident_types', ['parent_id'], unique=False)
    op.create_table('organizations',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organizations_parent_id'), 'organizations', ['parent_id'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_is_deleted'), 'permissions', ['is_deleted'], unique=False)
    op.create_table('personnel_roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_roles_code'), 'personnel_roles', ['code'], unique=True)
    op.create_index(op.f('ix_personnel_roles_is_deleted'), 'personnel_roles', ['is_deleted'], unique=False)
    op.create_table('resource_types',
    sa.Column('category', sa.Enum('STATION', 'VEHICLE', 'PERSONNEL', 'EQUIPMENT', 'INFRASTRUCTURE', 'FACILITY', name='resource_category'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_types_category'), 'resource_types', ['category'], unique=False)
    op.create_index(op.f('ix_resource_types_code'), 'resource_types', ['code'], unique=True)
    op.create_index(op.f('ix_resource_types_is_deleted'), 'resource_types', ['is_deleted'], unique=False)
    op.create_table('roles',
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.create_table('vehicle_types',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_types_code'), 'vehicle_types', ['code'], unique=True)
    op.create_index(op.f('ix_vehicle_types_is_deleted'), 'vehicle_types', ['is_deleted'], unique=False)
    op.create_table('incident_type_capabilities',
    sa.Column('incident_type_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_type_id', 'capability_id', name='uq_incident_type_capability')
    )
    op.create_index(op.f('ix_incident_type_capabilities_capability_id'), 'incident_type_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_incident_type_capabilities_incident_type_id'), 'incident_type_capabilities', ['incident_type_id'], unique=False)
    op.create_index(op.f('ix_incident_type_capabilities_is_deleted'), 'incident_type_capabilities', ['is_deleted'], unique=False)
    op.create_geospatial_table('locations',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('administrative_area_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['administrative_area_id'], ['administrative_areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_locations_geom', 'locations', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_locations_administrative_area_id'), 'locations', ['administrative_area_id'], unique=False)
    op.create_index(op.f('ix_locations_is_deleted'), 'locations', ['is_deleted'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_is_deleted'), 'role_permissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_geospatial_table('resources',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('resource_type_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('availability_status_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('home_station_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['availability_status_id'], ['availability_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_station_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resource_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_resources_code')
    )
    op.create_geospatial_index('idx_resources_geom', 'resources', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_resources_active', 'resources', ['organization_id', 'resource_type_id', 'availability_status_id'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_resources_availability_status_id'), 'resources', ['availability_status_id'], unique=False)
    op.create_index(op.f('ix_resources_code'), 'resources', ['code'], unique=False)
    op.create_index(op.f('ix_resources_home_station_id'), 'resources', ['home_station_id'], unique=False)
    op.create_index(op.f('ix_resources_is_deleted'), 'resources', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_resources_location_id'), 'resources', ['location_id'], unique=False)
    op.create_index(op.f('ix_resources_organization_id'), 'resources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resources_resource_type_id'), 'resources', ['resource_type_id'], unique=False)
    op.create_geospatial_table('coordinate_history',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_coordinate_history_geom', 'coordinate_history', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_coordinate_history_is_deleted'), 'coordinate_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_coordinate_history_resource_id'), 'coordinate_history', ['resource_id'], unique=False)
    op.create_index('ix_coordinate_history_resource_time', 'coordinate_history', ['resource_id', 'recorded_at'], unique=False)
    op.create_geospatial_table('coverage_areas',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('administrative_area_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('area', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['administrative_area_id'], ['administrative_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_coverage_areas_area', 'coverage_areas', ['area'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_coverage_areas_administrative_area_id'), 'coverage_areas', ['administrative_area_id'], unique=False)
    op.create_index(op.f('ix_coverage_areas_is_deleted'), 'coverage_areas', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_coverage_areas_resource_id'), 'coverage_areas', ['resource_id'], unique=False)
    op.create_table('equipment',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('equipment_type_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('inventory_number', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_service_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_equipment_equipment_type_id'), 'equipment', ['equipment_type_id'], unique=False)
    op.create_index(op.f('ix_equipment_is_deleted'), 'equipment', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_equipment_resource_id'), 'equipment', ['resource_id'], unique=True)
    op.create_table('personnel',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('personnel_role_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('rank', sa.String(length=64), nullable=True),
    sa.Column('badge_number', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_role_id'], ['personnel_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_number')
    )
    op.create_index(op.f('ix_personnel_is_deleted'), 'personnel', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_personnel_personnel_role_id'), 'personnel', ['personnel_role_id'], unique=False)
    op.create_index(op.f('ix_personnel_resource_id'), 'personnel', ['resource_id'], unique=True)
    op.create_table('resource_capabilities',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'capability_id', name='uq_resource_capability')
    )
    op.create_index(op.f('ix_resource_capabilities_capability_id'), 'resource_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_resource_capabilities_is_deleted'), 'resource_capabilities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_resource_capabilities_resource_id'), 'resource_capabilities', ['resource_id'], unique=False)
    op.create_table('stations',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('station_number', sa.String(length=32), nullable=True),
    sa.Column('garage_capacity', sa.Integer(), nullable=True),
    sa.Column('staff_capacity', sa.Integer(), nullable=True),
    sa.Column('is_round_the_clock', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_is_deleted'), 'stations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_stations_resource_id'), 'stations', ['resource_id'], unique=True)
    op.create_table('vehicles',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=True),
    sa.Column('crew_capacity', sa.Integer(), nullable=True),
    sa.Column('water_capacity_l', sa.Integer(), nullable=True),
    sa.Column('foam_capacity_l', sa.Integer(), nullable=True),
    sa.Column('pump_capacity_l_min', sa.Integer(), nullable=True),
    sa.Column('ladder_height_m', sa.Float(), nullable=True),
    sa.Column('year_manufactured', sa.Integer(), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_index(op.f('ix_vehicles_is_deleted'), 'vehicles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_vehicles_resource_id'), 'vehicles', ['resource_id'], unique=True)
    op.create_index(op.f('ix_vehicles_vehicle_type_id'), 'vehicles', ['vehicle_type_id'], unique=False)
    op.create_table('coverage_area_incident_types',
    sa.Column('coverage_area_id', sa.UUID(), nullable=False),
    sa.Column('incident_type_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['coverage_area_id'], ['coverage_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coverage_area_id', 'incident_type_id', name='uq_coverage_area_incident_type')
    )
    op.create_index(op.f('ix_coverage_area_incident_types_coverage_area_id'), 'coverage_area_incident_types', ['coverage_area_id'], unique=False)
    op.create_index(op.f('ix_coverage_area_incident_types_incident_type_id'), 'coverage_area_incident_types', ['incident_type_id'], unique=False)
    op.create_index(op.f('ix_coverage_area_incident_types_is_deleted'), 'coverage_area_incident_types', ['is_deleted'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('personnel_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_personnel_id'), 'users', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'DISPATCH', 'STATUS_CHANGE', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_index('ix_audit_logs_user_time', 'audit_logs', ['user_id', 'occurred_at'], unique=False)
    op.create_table('status_history',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('from_status_id', sa.UUID(), nullable=True),
    sa.Column('to_status_id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_status_id'], ['availability_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_status_id'], ['availability_statuses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_is_deleted'), 'status_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_status_history_resource_id'), 'status_history', ['resource_id'], unique=False)
    op.create_index('ix_status_history_resource_time', 'status_history', ['resource_id', 'changed_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_is_deleted'), 'user_roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_is_deleted'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_status_history_resource_time', table_name='status_history')
    op.drop_index(op.f('ix_status_history_resource_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_is_deleted'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index('ix_audit_logs_user_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_personnel_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_coverage_area_incident_types_is_deleted'), table_name='coverage_area_incident_types')
    op.drop_index(op.f('ix_coverage_area_incident_types_incident_type_id'), table_name='coverage_area_incident_types')
    op.drop_index(op.f('ix_coverage_area_incident_types_coverage_area_id'), table_name='coverage_area_incident_types')
    op.drop_table('coverage_area_incident_types')
    op.drop_index(op.f('ix_vehicles_vehicle_type_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_resource_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_is_deleted'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_stations_resource_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_is_deleted'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_resource_capabilities_resource_id'), table_name='resource_capabilities')
    op.drop_index(op.f('ix_resource_capabilities_is_deleted'), table_name='resource_capabilities')
    op.drop_index(op.f('ix_resource_capabilities_capability_id'), table_name='resource_capabilities')
    op.drop_table('resource_capabilities')
    op.drop_index(op.f('ix_personnel_resource_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_personnel_role_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_is_deleted'), table_name='personnel')
    op.drop_table('personnel')
    op.drop_index(op.f('ix_equipment_resource_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_is_deleted'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_type_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_coverage_areas_resource_id'), table_name='coverage_areas')
    op.drop_index(op.f('ix_coverage_areas_is_deleted'), table_name='coverage_areas')
    op.drop_index(op.f('ix_coverage_areas_administrative_area_id'), table_name='coverage_areas')
    op.drop_geospatial_index('idx_coverage_areas_area', table_name='coverage_areas', postgresql_using='gist', column_name='area')
    op.drop_geospatial_table('coverage_areas')
    op.drop_index('ix_coordinate_history_resource_time', table_name='coordinate_history')
    op.drop_index(op.f('ix_coordinate_history_resource_id'), table_name='coordinate_history')
    op.drop_index(op.f('ix_coordinate_history_is_deleted'), table_name='coordinate_history')
    op.drop_geospatial_index('idx_coordinate_history_geom', table_name='coordinate_history', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('coordinate_history')
    op.drop_index(op.f('ix_resources_resource_type_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_organization_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_location_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_deleted'), table_name='resources')
    op.drop_index(op.f('ix_resources_home_station_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_code'), table_name='resources')
    op.drop_index(op.f('ix_resources_availability_status_id'), table_name='resources')
    op.drop_index('ix_resources_active', table_name='resources', postgresql_where=sa.text('is_deleted = false'))
    op.drop_geospatial_index('idx_resources_geom', table_name='resources', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('resources')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_is_deleted'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_locations_is_deleted'), table_name='locations')
    op.drop_index(op.f('ix_locations_administrative_area_id'), table_name='locations')
    op.drop_geospatial_index('idx_locations_geom', table_name='locations', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('locations')
    op.drop_index(op.f('ix_incident_type_capabilities_is_deleted'), table_name='incident_type_capabilities')
    op.drop_index(op.f('ix_incident_type_capabilities_incident_type_id'), table_name='incident_type_capabilities')
    op.drop_index(op.f('ix_incident_type_capabilities_capability_id'), table_name='incident_type_capabilities')
    op.drop_table('incident_type_capabilities')
    op.drop_index(op.f('ix_vehicle_types_is_deleted'), table_name='vehicle_types')
    op.drop_index(op.f('ix_vehicle_types_code'), table_name='vehicle_types')
    op.drop_table('vehicle_types')
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resource_types_is_deleted'), table_name='resource_types')
    op.drop_index(op.f('ix_resource_types_code'), table_name='resource_types')
    op.drop_index(op.f('ix_resource_types_category'), table_name='resource_types')
    op.drop_table('resource_types')
    op.drop_index(op.f('ix_personnel_roles_is_deleted'), table_name='personnel_roles')
    op.drop_index(op.f('ix_personnel_roles_code'), table_name='personnel_roles')
    op.drop_table('personnel_roles')
    op.drop_index(op.f('ix_permissions_is_deleted'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_parent_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_incident_types_parent_id'), table_name='incident_types')
    op.drop_index(op.f('ix_incident_types_is_deleted'), table_name='incident_types')
    op.drop_index(op.f('ix_incident_types_code'), table_name='incident_types')
    op.drop_table('incident_types')
    op.drop_index(op.f('ix_equipment_types_is_deleted'), table_name='equipment_types')
    op.drop_index(op.f('ix_equipment_types_code'), table_name='equipment_types')
    op.drop_table('equipment_types')
    op.drop_index(op.f('ix_capabilities_is_deleted'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_code'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_availability_statuses_is_deleted'), table_name='availability_statuses')
    op.drop_index(op.f('ix_availability_statuses_code'), table_name='availability_statuses')
    op.drop_table('availability_statuses')
    op.drop_index(op.f('ix_administrative_areas_parent_id'), table_name='administrative_areas')
    op.drop_index(op.f('ix_administrative_areas_is_deleted'), table_name='administrative_areas')
    op.drop_index(op.f('ix_administrative_areas_code'), table_name='administrative_areas')
    op.drop_geospatial_index('idx_administrative_areas_boundary', table_name='administrative_areas', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('administrative_areas')
    # Drop the native ENUM types explicitly: dropping the tables does not remove
    # them, and leaving them behind would break a subsequent upgrade.
    op.execute("DROP TYPE IF EXISTS audit_action")
    op.execute("DROP TYPE IF EXISTS resource_category")
    # ### end Alembic commands ###
