"""incident management

Revision ID: 14c2475154fb
Revises: be056670ec62
Create Date: 2026-07-25 19:21:12.280768+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.incidents.models.types import NEW_ENUMS

# revision identifiers, used by Alembic.
revision: str = '14c2475154fb'
down_revision: str | None = 'be056670ec62'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create the new native enum types once.
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('incident_type_id', sa.UUID(), nullable=True),
    sa.Column('category', postgresql.ENUM('fire', 'road_accident', 'rescue', 'chemical', 'wildfire', 'false_alarm', 'special_ops', 'service_ops', 'other', name='incident_category', create_type=False), server_default='other', nullable=False),
    sa.Column('source', postgresql.ENUM('phone', 'radio', 'system', 'patrol', 'manual', 'other', name='incident_source', create_type=False), server_default='phone', nullable=False),
    sa.Column('status', postgresql.ENUM('created', 'checking', 'confirmed', 'selecting', 'dispatch_confirmed', 'dispatched', 'on_scene', 'localized', 'liquidated', 'completed', 'archived', 'cancelled', name='incident_status', create_type=False), server_default='created', nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'normal', 'high', 'critical', name='incident_priority', create_type=False), server_default='normal', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('administrative_area_id', sa.UUID(), nullable=True),
    sa.Column('danger_level', sa.String(length=32), nullable=True),
    sa.Column('object_type', sa.String(length=128), nullable=True),
    sa.Column('reporter_name', sa.String(length=255), nullable=True),
    sa.Column('reporter_contact', sa.String(length=128), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['administrative_area_id'], ['administrative_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_category'), 'incidents', ['category'], unique=False)
    op.create_index(op.f('ix_incidents_incident_type_id'), 'incidents', ['incident_type_id'], unique=False)
    op.create_index(op.f('ix_incidents_is_deleted'), 'incidents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_incidents_number'), 'incidents', ['number'], unique=True)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_status_created', 'incidents', ['status', 'created_at'], unique=False)
    op.create_table('incident_attachments',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('kind', postgresql.ENUM('photo', 'document', 'scheme', 'other', name='incident_attachment_kind', create_type=False), server_default='other', nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_ref', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_attachments_incident_id'), 'incident_attachments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_attachments_is_deleted'), 'incident_attachments', ['is_deleted'], unique=False)
    op.create_table('incident_comments',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('text', sa.String(length=4096), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_comments_incident_id'), 'incident_comments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_comments_is_deleted'), 'incident_comments', ['is_deleted'], unique=False)
    op.create_table('incident_dispatches',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='primary', nullable=False),
    sa.Column('status', postgresql.ENUM('assigned', 'en_route', 'on_scene', 'returning', 'released', 'cancelled', name='incident_dispatch_status', create_type=False), server_default='assigned', nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'resource_id', name='uq_incident_dispatch')
    )
    op.create_index(op.f('ix_incident_dispatches_incident_id'), 'incident_dispatches', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_dispatches_is_deleted'), 'incident_dispatches', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_incident_dispatches_resource_id'), 'incident_dispatches', ['resource_id'], unique=False)
    op.create_table('incident_history',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=1024), nullable=True),
    sa.Column('new_value', sa.String(length=1024), nullable=True),
    sa.Column('change_source', postgresql.ENUM('dispatcher', 'system', 'integration', name='incident_change_source', create_type=False), server_default='dispatcher', nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_history_incident_id'), 'incident_history', ['incident_id'], unique=False)
    op.create_index('ix_incident_history_incident_time', 'incident_history', ['incident_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_incident_history_is_deleted'), 'incident_history', ['is_deleted'], unique=False)
    op.create_table('incident_locations',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('administrative_area_id', sa.UUID(), nullable=True),
    sa.Column('accuracy', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['administrative_area_id'], ['administrative_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_locations_incident_id'), 'incident_locations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_locations_is_deleted'), 'incident_locations', ['is_deleted'], unique=False)
    op.create_table('incident_logs',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('level', sa.String(length=16), server_default='info', nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_logs_incident_id'), 'incident_logs', ['incident_id'], unique=False)
    op.create_index('ix_incident_logs_incident_time', 'incident_logs', ['incident_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_incident_logs_is_deleted'), 'incident_logs', ['is_deleted'], unique=False)
    op.create_table('incident_participants',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=128), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_participants_incident_id'), 'incident_participants', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_participants_is_deleted'), 'incident_participants', ['is_deleted'], unique=False)
    op.create_table('incident_recommendations',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['dispatch_recommendations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_recommendations_incident_id'), 'incident_recommendations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_recommendations_is_deleted'), 'incident_recommendations', ['is_deleted'], unique=False)
    op.create_table('incident_timeline',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('created', 'info_checked', 'confirmed', 'address_changed', 'category_changed', 'priority_changed', 'recommendation_requested', 'units_assigned', 'status_changed', 'comment_added', 'attachment_added', 'participant_added', 'closed', 'archived', name='incident_timeline_event', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=1024), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timeline_event_type'), 'incident_timeline', ['event_type'], unique=False)
    op.create_index(op.f('ix_incident_timeline_incident_id'), 'incident_timeline', ['incident_id'], unique=False)
    op.create_index('ix_incident_timeline_incident_time', 'incident_timeline', ['incident_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_incident_timeline_is_deleted'), 'incident_timeline', ['is_deleted'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_timeline_is_deleted'), table_name='incident_timeline')
    op.drop_index('ix_incident_timeline_incident_time', table_name='incident_timeline')
    op.drop_index(op.f('ix_incident_timeline_incident_id'), table_name='incident_timeline')
    op.drop_index(op.f('ix_incident_timeline_event_type'), table_name='incident_timeline')
    op.drop_table('incident_timeline')
    op.drop_index(op.f('ix_incident_recommendations_is_deleted'), table_name='incident_recommendations')
    op.drop_index(op.f('ix_incident_recommendations_incident_id'), table_name='incident_recommendations')
    op.drop_table('incident_recommendations')
    op.drop_index(op.f('ix_incident_participants_is_deleted'), table_name='incident_participants')
    op.drop_index(op.f('ix_incident_participants_incident_id'), table_name='incident_participants')
    op.drop_table('incident_participants')
    op.drop_index(op.f('ix_incident_logs_is_deleted'), table_name='incident_logs')
    op.drop_index('ix_incident_logs_incident_time', table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_incident_id'), table_name='incident_logs')
    op.drop_table('incident_logs')
    op.drop_index(op.f('ix_incident_locations_is_deleted'), table_name='incident_locations')
    op.drop_index(op.f('ix_incident_locations_incident_id'), table_name='incident_locations')
    op.drop_table('incident_locations')
    op.drop_index(op.f('ix_incident_history_is_deleted'), table_name='incident_history')
    op.drop_index('ix_incident_history_incident_time', table_name='incident_history')
    op.drop_index(op.f('ix_incident_history_incident_id'), table_name='incident_history')
    op.drop_table('incident_history')
    op.drop_index(op.f('ix_incident_dispatches_resource_id'), table_name='incident_dispatches')
    op.drop_index(op.f('ix_incident_dispatches_is_deleted'), table_name='incident_dispatches')
    op.drop_index(op.f('ix_incident_dispatches_incident_id'), table_name='incident_dispatches')
    op.drop_table('incident_dispatches')
    op.drop_index(op.f('ix_incident_comments_is_deleted'), table_name='incident_comments')
    op.drop_index(op.f('ix_incident_comments_incident_id'), table_name='incident_comments')
    op.drop_table('incident_comments')
    op.drop_index(op.f('ix_incident_attachments_is_deleted'), table_name='incident_attachments')
    op.drop_index(op.f('ix_incident_attachments_incident_id'), table_name='incident_attachments')
    op.drop_table('incident_attachments')
    op.drop_index('ix_incidents_status_created', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_number'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_is_deleted'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_type_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_category'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###


    # Drop the new native enum types.
    bind = op.get_bind()
    for enum_type in reversed(NEW_ENUMS):
        enum_type.drop(bind, checkfirst=True)
