"""resource management

Revision ID: ca0cd41c1454
Revises: 14c2475154fb
Create Date: 2026-07-26 00:05:29.702834+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.resources.models.types import NEW_ENUMS

# revision identifiers, used by Alembic.
revision: str = 'ca0cd41c1454'
down_revision: str | None = '14c2475154fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('rotation', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_code'), 'shifts', ['code'], unique=True)
    op.create_index(op.f('ix_shifts_is_deleted'), 'shifts', ['is_deleted'], unique=False)
    op.create_table('personnel_qualifications',
    sa.Column('personnel_resource_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', postgresql.ENUM('qualification', 'clearance', 'medical', name='personnel_qualification_kind', create_type=False), server_default='qualification', nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_qualifications_is_deleted'), 'personnel_qualifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_personnel_qualifications_personnel_resource_id'), 'personnel_qualifications', ['personnel_resource_id'], unique=False)
    op.create_table('vehicle_states',
    sa.Column('vehicle_resource_id', sa.UUID(), nullable=False),
    sa.Column('fuel_level_percent', sa.Integer(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('technical_condition', postgresql.ENUM('operational', 'needs_service', 'under_repair', 'decommissioned', name='vehicle_technical_condition', create_type=False), server_default='operational', nullable=False),
    sa.Column('last_service_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_service_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_resource_id', name='uq_vehicle_state')
    )
    op.create_index(op.f('ix_vehicle_states_is_deleted'), 'vehicle_states', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_vehicle_states_vehicle_resource_id'), 'vehicle_states', ['vehicle_resource_id'], unique=False)
    op.create_table('units',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('call_sign', sa.String(length=64), nullable=True),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_resource_id', sa.UUID(), nullable=True),
    sa.Column('availability_status_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['availability_status_id'], ['availability_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_code'), 'units', ['code'], unique=True)
    op.create_index(op.f('ix_units_is_active'), 'units', ['is_active'], unique=False)
    op.create_index(op.f('ix_units_is_deleted'), 'units', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_units_organization_id'), 'units', ['organization_id'], unique=False)
    op.create_index(op.f('ix_units_station_id'), 'units', ['station_id'], unique=False)
    op.create_index(op.f('ix_units_vehicle_resource_id'), 'units', ['vehicle_resource_id'], unique=False)
    op.create_table('crews',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('is_on_duty', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crews_code'), 'crews', ['code'], unique=True)
    op.create_index(op.f('ix_crews_is_deleted'), 'crews', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crews_is_on_duty'), 'crews', ['is_on_duty'], unique=False)
    op.create_index(op.f('ix_crews_shift_id'), 'crews', ['shift_id'], unique=False)
    op.create_index(op.f('ix_crews_unit_id'), 'crews', ['unit_id'], unique=False)
    op.create_table('crew_members',
    sa.Column('crew_id', sa.UUID(), nullable=False),
    sa.Column('personnel_resource_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('is_commander', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personnel_resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crew_id', 'personnel_resource_id', name='uq_crew_member')
    )
    op.create_index(op.f('ix_crew_members_crew_id'), 'crew_members', ['crew_id'], unique=False)
    op.create_index(op.f('ix_crew_members_is_deleted'), 'crew_members', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crew_members_personnel_resource_id'), 'crew_members', ['personnel_resource_id'], unique=False)
    op.create_table('duty_rosters',
    sa.Column('roster_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('crew_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roster_date', 'shift_id', 'crew_id', name='uq_duty_roster')
    )
    op.create_index(op.f('ix_duty_rosters_crew_id'), 'duty_rosters', ['crew_id'], unique=False)
    op.create_index(op.f('ix_duty_rosters_is_deleted'), 'duty_rosters', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_duty_rosters_roster_date'), 'duty_rosters', ['roster_date'], unique=False)
    op.create_index(op.f('ix_duty_rosters_shift_id'), 'duty_rosters', ['shift_id'], unique=False)
    op.create_table('resource_assignments',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=32), server_default='primary', nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'released', 'cancelled', name='resource_assignment_status', create_type=False), server_default='active', nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_assignments_incident_id'), 'resource_assignments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_resource_assignments_is_deleted'), 'resource_assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_resource_assignments_unit_id'), 'resource_assignments', ['unit_id'], unique=False)
    op.create_index('ix_resource_assignments_unit_status', 'resource_assignments', ['unit_id', 'status'], unique=False)
    op.create_table('resource_management_history',
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('crew_id', sa.UUID(), nullable=True),
    sa.Column('event_type', postgresql.ENUM('unit_status_changed', 'vehicle_status_changed', 'personnel_status_changed', 'crew_changed', 'crew_member_changed', 'assigned', 'returned', name='resource_event_type', create_type=False), nullable=False),
    sa.Column('from_value', sa.String(length=255), nullable=True),
    sa.Column('to_value', sa.String(length=255), nullable=True),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='dispatcher', nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_history_resource', 'resource_management_history', ['resource_id', 'occurred_at'], unique=False)
    op.create_index('ix_resource_history_time', 'resource_management_history', ['occurred_at'], unique=False)
    op.create_index('ix_resource_history_unit', 'resource_management_history', ['unit_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_resource_management_history_event_type'), 'resource_management_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_resource_management_history_incident_id'), 'resource_management_history', ['incident_id'], unique=False)
    op.create_index(op.f('ix_resource_management_history_is_deleted'), 'resource_management_history', ['is_deleted'], unique=False)
    # ### end Alembic commands ###

    # Seed the standard unit/vehicle/personnel statuses (data-driven, idempotent).
    op.execute(
        """
        INSERT INTO availability_statuses
            (id, code, name, is_operational, is_available_for_dispatch,
             sort_order, color, is_deleted, created_at, updated_at)
        VALUES
            (gen_random_uuid(),'on_duty','В боевом расчёте',true,true,10,'#2e7d32',false,now(),now()),
            (gen_random_uuid(),'free','Свободно',true,true,20,'#43a047',false,now(),now()),
            (gen_random_uuid(),'enroute','Следует к месту вызова',true,false,30,'#1e88e5',false,now(),now()),
            (gen_random_uuid(),'on_scene','Работает на месте',true,false,40,'#fb8c00',false,now(),now()),
            (gen_random_uuid(),'returning','Возвращается',true,false,50,'#8e24aa',false,now(),now()),
            (gen_random_uuid(),'maintenance','На обслуживании',false,false,60,'#757575',false,now(),now()),
            (gen_random_uuid(),'repair','На ремонте',false,false,70,'#e53935',false,now(),now()),
            (gen_random_uuid(),'unavailable','Недоступно',false,false,80,'#b71c1c',false,now(),now()),
            (gen_random_uuid(),'reserve','Резерв',true,false,90,'#00897b',false,now(),now())
        ON CONFLICT (code) DO NOTHING
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_management_history_is_deleted'), table_name='resource_management_history')
    op.drop_index(op.f('ix_resource_management_history_incident_id'), table_name='resource_management_history')
    op.drop_index(op.f('ix_resource_management_history_event_type'), table_name='resource_management_history')
    op.drop_index('ix_resource_history_unit', table_name='resource_management_history')
    op.drop_index('ix_resource_history_time', table_name='resource_management_history')
    op.drop_index('ix_resource_history_resource', table_name='resource_management_history')
    op.drop_table('resource_management_history')
    op.drop_index('ix_resource_assignments_unit_status', table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_unit_id'), table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_is_deleted'), table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_incident_id'), table_name='resource_assignments')
    op.drop_table('resource_assignments')
    op.drop_index(op.f('ix_duty_rosters_shift_id'), table_name='duty_rosters')
    op.drop_index(op.f('ix_duty_rosters_roster_date'), table_name='duty_rosters')
    op.drop_index(op.f('ix_duty_rosters_is_deleted'), table_name='duty_rosters')
    op.drop_index(op.f('ix_duty_rosters_crew_id'), table_name='duty_rosters')
    op.drop_table('duty_rosters')
    op.drop_index(op.f('ix_crew_members_personnel_resource_id'), table_name='crew_members')
    op.drop_index(op.f('ix_crew_members_is_deleted'), table_name='crew_members')
    op.drop_index(op.f('ix_crew_members_crew_id'), table_name='crew_members')
    op.drop_table('crew_members')
    op.drop_index(op.f('ix_crews_unit_id'), table_name='crews')
    op.drop_index(op.f('ix_crews_shift_id'), table_name='crews')
    op.drop_index(op.f('ix_crews_is_on_duty'), table_name='crews')
    op.drop_index(op.f('ix_crews_is_deleted'), table_name='crews')
    op.drop_index(op.f('ix_crews_code'), table_name='crews')
    op.drop_table('crews')
    op.drop_index(op.f('ix_units_vehicle_resource_id'), table_name='units')
    op.drop_index(op.f('ix_units_station_id'), table_name='units')
    op.drop_index(op.f('ix_units_organization_id'), table_name='units')
    op.drop_index(op.f('ix_units_is_deleted'), table_name='units')
    op.drop_index(op.f('ix_units_is_active'), table_name='units')
    op.drop_index(op.f('ix_units_code'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_vehicle_states_vehicle_resource_id'), table_name='vehicle_states')
    op.drop_index(op.f('ix_vehicle_states_is_deleted'), table_name='vehicle_states')
    op.drop_table('vehicle_states')
    op.drop_index(op.f('ix_personnel_qualifications_personnel_resource_id'), table_name='personnel_qualifications')
    op.drop_index(op.f('ix_personnel_qualifications_is_deleted'), table_name='personnel_qualifications')
    op.drop_table('personnel_qualifications')
    op.drop_index(op.f('ix_shifts_is_deleted'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_code'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###

    # Drop the new native enum types (seeded statuses are kept — they may be
    # referenced by existing resources).
    bind = op.get_bind()
    for enum_type in reversed(NEW_ENUMS):
        enum_type.drop(bind, checkfirst=True)
