"""dispatch recommendations

Revision ID: be056670ec62
Revises: 510711679a9c
Create Date: 2026-07-25 14:03:26.018362+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.dispatch.models.types import NEW_ENUMS

# revision identifiers, used by Alembic.
revision: str = 'be056670ec62'
down_revision: str | None = '510711679a9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create the new native enum types once (incident_complexity / rule_priority
    # already exist from the rules stage and are reused, not recreated).
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_recommendations',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('incident_type_id', sa.UUID(), nullable=False),
    sa.Column('complexity', postgresql.ENUM('simple', 'moderate', 'complex', 'critical', name='incident_complexity', create_type=False), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('administrative_area_id', sa.UUID(), nullable=True),
    sa.Column('danger_level', sa.String(length=32), nullable=True),
    sa.Column('priority', postgresql.ENUM('low', 'normal', 'high', 'critical', name='rule_priority', create_type=False), server_default='normal', nullable=False),
    sa.Column('status', postgresql.ENUM('recommended', 'partial', 'no_resources', name='dispatch_status', create_type=False), nullable=False),
    sa.Column('sufficient', sa.Boolean(), nullable=False),
    sa.Column('confidence', postgresql.ENUM('low', 'medium', 'high', name='recommendation_confidence', create_type=False), nullable=False),
    sa.Column('confidence_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('total_candidates', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_preview', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['administrative_area_id'], ['administrative_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispatch_rec_incident', 'dispatch_recommendations', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_dispatch_recommendations_incident_id'), 'dispatch_recommendations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_dispatch_recommendations_incident_type_id'), 'dispatch_recommendations', ['incident_type_id'], unique=False)
    op.create_index(op.f('ix_dispatch_recommendations_is_deleted'), 'dispatch_recommendations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dispatch_recommendations_is_preview'), 'dispatch_recommendations', ['is_preview'], unique=False)
    op.create_index(op.f('ix_dispatch_recommendations_status'), 'dispatch_recommendations', ['status'], unique=False)
    op.create_table('dispatch_capability_matches',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('capability_code', sa.String(length=64), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('provided_quantity', sa.Integer(), nullable=False),
    sa.Column('satisfied', sa.Boolean(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['dispatch_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_capability_matches_is_deleted'), 'dispatch_capability_matches', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dispatch_capability_matches_recommendation_id'), 'dispatch_capability_matches', ['recommendation_id'], unique=False)
    op.create_table('dispatch_decisions',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('decided', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', postgresql.ENUM('recommended', 'partial', 'no_resources', name='dispatch_status', create_type=False), nullable=False),
    sa.Column('used_rule_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('used_rule_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['dispatch_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', name='uq_dispatch_decision_rec')
    )
    op.create_index(op.f('ix_dispatch_decisions_incident_id'), 'dispatch_decisions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_dispatch_decisions_is_deleted'), 'dispatch_decisions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dispatch_decisions_recommendation_id'), 'dispatch_decisions', ['recommendation_id'], unique=False)
    op.create_table('dispatch_recommendation_summaries',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('primary_count', sa.Integer(), nullable=False),
    sa.Column('reserve_count', sa.Integer(), nullable=False),
    sa.Column('minimum_units', sa.Integer(), nullable=False),
    sa.Column('recommended_units', sa.Integer(), nullable=False),
    sa.Column('reserve_units', sa.Integer(), nullable=False),
    sa.Column('required_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('covered_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['dispatch_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', name='uq_dispatch_summary_rec')
    )
    op.create_index(op.f('ix_dispatch_recommendation_summaries_is_deleted'), 'dispatch_recommendation_summaries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dispatch_recommendation_summaries_recommendation_id'), 'dispatch_recommendation_summaries', ['recommendation_id'], unique=False)
    op.create_table('dispatch_recommendation_items',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('primary', 'reserve', name='recommendation_role', create_type=False), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('readiness', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['dispatch_recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_recommendation_items_is_deleted'), 'dispatch_recommendation_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dispatch_recommendation_items_recommendation_id'), 'dispatch_recommendation_items', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_dispatch_recommendation_items_resource_id'), 'dispatch_recommendation_items', ['resource_id'], unique=False)
    op.create_table('dispatch_resource_matches',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('readiness', sa.String(length=32), nullable=False),
    sa.Column('selected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('excluded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('exclusion_reason', postgresql.ENUM('unavailable_status', 'not_operational', 'not_deployable', 'out_of_service_zone', 'missing_capability', 'organization_constraint', 'manual_exclusion', 'not_selected', name='dispatch_exclusion_reason', create_type=False), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['dispatch_recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_resource_matches_is_deleted'), 'dispatch_resource_matches', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dispatch_resource_matches_recommendation_id'), 'dispatch_resource_matches', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_dispatch_resource_matches_resource_id'), 'dispatch_resource_matches', ['resource_id'], unique=False)
    op.create_table('dispatch_recommendation_reasons',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['dispatch_recommendation_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['dispatch_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_recommendation_reasons_is_deleted'), 'dispatch_recommendation_reasons', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dispatch_recommendation_reasons_item_id'), 'dispatch_recommendation_reasons', ['item_id'], unique=False)
    op.create_index(op.f('ix_dispatch_recommendation_reasons_recommendation_id'), 'dispatch_recommendation_reasons', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_recommendation_reasons_recommendation_id'), table_name='dispatch_recommendation_reasons')
    op.drop_index(op.f('ix_dispatch_recommendation_reasons_item_id'), table_name='dispatch_recommendation_reasons')
    op.drop_index(op.f('ix_dispatch_recommendation_reasons_is_deleted'), table_name='dispatch_recommendation_reasons')
    op.drop_table('dispatch_recommendation_reasons')
    op.drop_index(op.f('ix_dispatch_resource_matches_resource_id'), table_name='dispatch_resource_matches')
    op.drop_index(op.f('ix_dispatch_resource_matches_recommendation_id'), table_name='dispatch_resource_matches')
    op.drop_index(op.f('ix_dispatch_resource_matches_is_deleted'), table_name='dispatch_resource_matches')
    op.drop_table('dispatch_resource_matches')
    op.drop_index(op.f('ix_dispatch_recommendation_items_resource_id'), table_name='dispatch_recommendation_items')
    op.drop_index(op.f('ix_dispatch_recommendation_items_recommendation_id'), table_name='dispatch_recommendation_items')
    op.drop_index(op.f('ix_dispatch_recommendation_items_is_deleted'), table_name='dispatch_recommendation_items')
    op.drop_table('dispatch_recommendation_items')
    op.drop_index(op.f('ix_dispatch_recommendation_summaries_recommendation_id'), table_name='dispatch_recommendation_summaries')
    op.drop_index(op.f('ix_dispatch_recommendation_summaries_is_deleted'), table_name='dispatch_recommendation_summaries')
    op.drop_table('dispatch_recommendation_summaries')
    op.drop_index(op.f('ix_dispatch_decisions_recommendation_id'), table_name='dispatch_decisions')
    op.drop_index(op.f('ix_dispatch_decisions_is_deleted'), table_name='dispatch_decisions')
    op.drop_index(op.f('ix_dispatch_decisions_incident_id'), table_name='dispatch_decisions')
    op.drop_table('dispatch_decisions')
    op.drop_index(op.f('ix_dispatch_capability_matches_recommendation_id'), table_name='dispatch_capability_matches')
    op.drop_index(op.f('ix_dispatch_capability_matches_is_deleted'), table_name='dispatch_capability_matches')
    op.drop_table('dispatch_capability_matches')
    op.drop_index(op.f('ix_dispatch_recommendations_status'), table_name='dispatch_recommendations')
    op.drop_index(op.f('ix_dispatch_recommendations_is_preview'), table_name='dispatch_recommendations')
    op.drop_index(op.f('ix_dispatch_recommendations_is_deleted'), table_name='dispatch_recommendations')
    op.drop_index(op.f('ix_dispatch_recommendations_incident_type_id'), table_name='dispatch_recommendations')
    op.drop_index(op.f('ix_dispatch_recommendations_incident_id'), table_name='dispatch_recommendations')
    op.drop_index('ix_dispatch_rec_incident', table_name='dispatch_recommendations')
    op.drop_table('dispatch_recommendations')
    # ### end Alembic commands ###

    # Drop the new native enum types (reused rules enums are left in place).
    bind = op.get_bind()
    for enum_type in reversed(NEW_ENUMS):
        enum_type.drop(bind, checkfirst=True)
