"""ai audit log

Revision ID: 0d42a2ab8331
Revises: fdfdd3879577
Create Date: 2026-07-26 10:09:21.392112+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.ai.models.types import NEW_ENUMS

# revision identifiers, used by Alembic.
revision: str = '0d42a2ab8331'
down_revision: str | None = 'fdfdd3879577'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create the new native enum types once.
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_log',
    sa.Column('capability', postgresql.ENUM('transcribe', 'extract_entities', 'classify_incident', 'summarize', 'analyze', name='ai_audit_capability', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('success', 'error', name='ai_audit_status', create_type=False), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_audit_capability_created', 'ai_audit_log', ['capability', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_audit_log_call_id'), 'ai_audit_log', ['call_id'], unique=False)
    op.create_index(op.f('ix_ai_audit_log_capability'), 'ai_audit_log', ['capability'], unique=False)
    op.create_index(op.f('ix_ai_audit_log_incident_id'), 'ai_audit_log', ['incident_id'], unique=False)
    op.create_index(op.f('ix_ai_audit_log_is_deleted'), 'ai_audit_log', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_audit_log_status'), 'ai_audit_log', ['status'], unique=False)
    op.create_index('ix_ai_audit_provider_created', 'ai_audit_log', ['provider', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_audit_provider_created', table_name='ai_audit_log')
    op.drop_index(op.f('ix_ai_audit_log_status'), table_name='ai_audit_log')
    op.drop_index(op.f('ix_ai_audit_log_is_deleted'), table_name='ai_audit_log')
    op.drop_index(op.f('ix_ai_audit_log_incident_id'), table_name='ai_audit_log')
    op.drop_index(op.f('ix_ai_audit_log_capability'), table_name='ai_audit_log')
    op.drop_index(op.f('ix_ai_audit_log_call_id'), table_name='ai_audit_log')
    op.drop_index('ix_ai_audit_capability_created', table_name='ai_audit_log')
    op.drop_table('ai_audit_log')
    # ### end Alembic commands ###

    # Drop the new native enum types.
    bind = op.get_bind()
    for enum_type in reversed(NEW_ENUMS):
        enum_type.drop(bind, checkfirst=True)
