"""rules infrastructure

Revision ID: 510711679a9c
Revises: ef914db8e6d0
Create Date: 2026-07-25 09:40:30.028469+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.rules.models.types import NEW_ENUMS

# revision identifiers, used by Alembic.
revision: str = '510711679a9c'
down_revision: str | None = 'ef914db8e6d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the new native enum types exactly once (the column types use
    # create_type=False). resource_category already exists (Stage 2).
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.create(bind, checkfirst=True)
    op.create_table('rule_categories',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_categories_code'), 'rule_categories', ['code'], unique=True)
    op.create_index(op.f('ix_rule_categories_is_deleted'), 'rule_categories', ['is_deleted'], unique=False)
    op.create_table('rule_sets',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_sets_code'), 'rule_sets', ['code'], unique=True)
    op.create_index(op.f('ix_rule_sets_is_deleted'), 'rule_sets', ['is_deleted'], unique=False)
    op.create_table('rules',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['rule_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_category_id'), 'rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_rules_code'), 'rules', ['code'], unique=True)
    op.create_index(op.f('ix_rules_is_deleted'), 'rules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rules_rule_set_id'), 'rules', ['rule_set_id'], unique=False)
    op.create_table('rule_incident_categories',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('complexity', postgresql.ENUM('simple', 'moderate', 'complex', 'critical', name='incident_complexity', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'complexity', name='uq_rule_incident_category')
    )
    op.create_index(op.f('ix_rule_incident_categories_is_deleted'), 'rule_incident_categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rule_incident_categories_rule_id'), 'rule_incident_categories', ['rule_id'], unique=False)
    op.create_table('rule_incident_types',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('incident_type_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'incident_type_id', name='uq_rule_incident_type')
    )
    op.create_index(op.f('ix_rule_incident_types_incident_type_id'), 'rule_incident_types', ['incident_type_id'], unique=False)
    op.create_index(op.f('ix_rule_incident_types_is_deleted'), 'rule_incident_types', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rule_incident_types_rule_id'), 'rule_incident_types', ['rule_id'], unique=False)
    op.create_table('rule_tags',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'tag', name='uq_rule_tag')
    )
    op.create_index(op.f('ix_rule_tags_is_deleted'), 'rule_tags', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rule_tags_rule_id'), 'rule_tags', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rule_tags_tag'), 'rule_tags', ['tag'], unique=False)
    op.create_table('rule_versions',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'published', 'archived', 'deprecated', name='rule_status', create_type=False), server_default='draft', nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'normal', 'high', 'critical', name='rule_priority', create_type=False), server_default='normal', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version_number', name='uq_rule_version_number')
    )
    op.create_index(op.f('ix_rule_versions_is_active'), 'rule_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_rule_versions_is_deleted'), 'rule_versions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rule_versions_rule_id'), 'rule_versions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rule_versions_status'), 'rule_versions', ['status'], unique=False)
    op.create_index('uq_rule_active_version', 'rule_versions', ['rule_id'], unique=True, postgresql_where=sa.text('is_active AND NOT is_deleted'))
    op.create_table('rule_actions',
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('action_type', postgresql.ENUM('require_resources', 'require_capability', 'set_priority', 'set_reserve', 'escalate', 'notify', 'custom', name='rule_action_type', create_type=False), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_actions_is_deleted'), 'rule_actions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rule_actions_rule_version_id'), 'rule_actions', ['rule_version_id'], unique=False)
    op.create_table('rule_capability_requirements',
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('capability_code', sa.String(length=64), nullable=False),
    sa.Column('min_quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('mandatory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_version_id', 'capability_code', name='uq_rule_capability_req')
    )
    op.create_index(op.f('ix_rule_capability_requirements_is_deleted'), 'rule_capability_requirements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rule_capability_requirements_rule_version_id'), 'rule_capability_requirements', ['rule_version_id'], unique=False)
    op.create_table('rule_conditions',
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('condition_type', postgresql.ENUM('incident_type', 'incident_complexity', 'time_of_day', 'administrative_area', 'object_type', 'priority', 'resource_availability', 'capability', name='rule_condition_type', create_type=False), nullable=False),
    sa.Column('operator', postgresql.ENUM('eq', 'neq', 'in', 'not_in', 'gte', 'lte', 'between', 'exists', 'contains', name='rule_condition_operator', create_type=False), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_conditions_is_deleted'), 'rule_conditions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rule_conditions_rule_version_id'), 'rule_conditions', ['rule_version_id'], unique=False)
    op.create_table('rule_history',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=True),
    sa.Column('action', postgresql.ENUM('created', 'updated', 'version_created', 'published', 'activated', 'archived', 'deprecated', 'deleted', name='rule_history_action', create_type=False), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_history_action'), 'rule_history', ['action'], unique=False)
    op.create_index(op.f('ix_rule_history_is_deleted'), 'rule_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rule_history_rule_id'), 'rule_history', ['rule_id'], unique=False)
    op.create_index('ix_rule_history_rule_time', 'rule_history', ['rule_id', 'occurred_at'], unique=False)
    op.create_table('rule_resource_requirements',
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('resource_category', postgresql.ENUM('STATION', 'VEHICLE', 'PERSONNEL', 'EQUIPMENT', 'INFRASTRUCTURE', 'FACILITY', name='resource_category', create_type=False), nullable=False),
    sa.Column('vehicle_type_code', sa.String(length=64), nullable=True),
    sa.Column('min_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recommended_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserve_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'normal', 'high', 'critical', name='rule_priority', create_type=False), server_default='normal', nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_resource_requirements_is_deleted'), 'rule_resource_requirements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rule_resource_requirements_rule_version_id'), 'rule_resource_requirements', ['rule_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_resource_requirements_rule_version_id'), table_name='rule_resource_requirements')
    op.drop_index(op.f('ix_rule_resource_requirements_is_deleted'), table_name='rule_resource_requirements')
    op.drop_table('rule_resource_requirements')
    op.drop_index('ix_rule_history_rule_time', table_name='rule_history')
    op.drop_index(op.f('ix_rule_history_rule_id'), table_name='rule_history')
    op.drop_index(op.f('ix_rule_history_is_deleted'), table_name='rule_history')
    op.drop_index(op.f('ix_rule_history_action'), table_name='rule_history')
    op.drop_table('rule_history')
    op.drop_index(op.f('ix_rule_conditions_rule_version_id'), table_name='rule_conditions')
    op.drop_index(op.f('ix_rule_conditions_is_deleted'), table_name='rule_conditions')
    op.drop_table('rule_conditions')
    op.drop_index(op.f('ix_rule_capability_requirements_rule_version_id'), table_name='rule_capability_requirements')
    op.drop_index(op.f('ix_rule_capability_requirements_is_deleted'), table_name='rule_capability_requirements')
    op.drop_table('rule_capability_requirements')
    op.drop_index(op.f('ix_rule_actions_rule_version_id'), table_name='rule_actions')
    op.drop_index(op.f('ix_rule_actions_is_deleted'), table_name='rule_actions')
    op.drop_table('rule_actions')
    op.drop_index('uq_rule_active_version', table_name='rule_versions', postgresql_where=sa.text('is_active AND NOT is_deleted'))
    op.drop_index(op.f('ix_rule_versions_status'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_rule_id'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_is_deleted'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_is_active'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_rule_tags_tag'), table_name='rule_tags')
    op.drop_index(op.f('ix_rule_tags_rule_id'), table_name='rule_tags')
    op.drop_index(op.f('ix_rule_tags_is_deleted'), table_name='rule_tags')
    op.drop_table('rule_tags')
    op.drop_index(op.f('ix_rule_incident_types_rule_id'), table_name='rule_incident_types')
    op.drop_index(op.f('ix_rule_incident_types_is_deleted'), table_name='rule_incident_types')
    op.drop_index(op.f('ix_rule_incident_types_incident_type_id'), table_name='rule_incident_types')
    op.drop_table('rule_incident_types')
    op.drop_index(op.f('ix_rule_incident_categories_rule_id'), table_name='rule_incident_categories')
    op.drop_index(op.f('ix_rule_incident_categories_is_deleted'), table_name='rule_incident_categories')
    op.drop_table('rule_incident_categories')
    op.drop_index(op.f('ix_rules_rule_set_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_is_deleted'), table_name='rules')
    op.drop_index(op.f('ix_rules_code'), table_name='rules')
    op.drop_index(op.f('ix_rules_category_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_rule_sets_is_deleted'), table_name='rule_sets')
    op.drop_index(op.f('ix_rule_sets_code'), table_name='rule_sets')
    op.drop_table('rule_sets')
    op.drop_index(op.f('ix_rule_categories_is_deleted'), table_name='rule_categories')
    op.drop_index(op.f('ix_rule_categories_code'), table_name='rule_categories')
    op.drop_table('rule_categories')
    # Drop the new native enum types (resource_category is left in place).
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
